### ISSUE TITLE
Fail gracefully if tekton APIs are not available 

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-tekton#1]
Check if Tekton APIs are available on the cluster and display a message that indicates that Tekton is not available. 

Additionally we should also cover the case where tekton is installed but the current user does not have the privileges to interact with tekton resources.

**Comment by sudhirverma** [comment]
As discussed with tekton team there is a command to check `OpenShift Pipelines Operator ` is install or not command to check pipelines operator: `oc explain pipeline.tekton.dev` but when we install the `pipelines operator` and  then we uninstall `pipeline operator` it doesn't delete the resources,  
`oc explain pipeline.tekton.dev` command shows the resources are still present after the uninstalling the `OpenShift Pipelines Operator ` from operatorhub.

to check current user has privileges to interact with tekton resources or not command is `oc auth can-i create subscriptions.operators.coreos.com`

cc: @hrishin

**Comment by hrishin** [comment]
> Check if Tekton APIs are available on the cluster and display a message that indicates that Tekton is not available.

`oc explain pipeline.tekton.dev` or `oc get pipeline.tekton.dev` should do the trick here if command status returned as non-zero.

> Additionally we should also cover the case where tekton is installed but the current user does not have the privileges to interact with Tekton resources.

For this case `oc auth can-i create pipeline.tekton.dev` should help here.

**Comment by vdemeester** [comment]
This needs to work on a non openshift-pipelines instance too 🦸🏻‍♂️

**Comment by hrishin** [comment]
@vdemeester it will not work in OpenShift pipelines? :thinking:

**Comment by vdemeester** [comment]
Ah I thought `pipeline.tekton.dev` was specific to our openshift-pipelines controller. Turns out it is `operator.tekton.dev` :stuck_out_tongue:. The API group `pipeline.tekton.dev` doesn't exist (yet?), it's all in `tekton.dev` as of now.

```
~ λ oc api-resources | grep tekton
config                                                 operator.tekton.dev                   false        Config
clustertasks                                           tekton.dev                            false        ClusterTask
conditions                                             tekton.dev                            true         Condition
eventlisteners                        el               tekton.dev                            true         EventListener
pipelineresources                                      tekton.dev                            true         PipelineResource
pipelineruns                          pr,prs           tekton.dev                            true         PipelineRun
pipelines                                              tekton.dev                            true         Pipeline
taskruns                              tr,trs           tekton.dev                            true         TaskRun
tasks                                                  tekton.dev                            true         Task
triggerbindings                       tb               tekton.dev                            true         TriggerBinding
triggertemplates                      tt               tekton.dev                            true         TriggerTemplate
```

We will need to discuss that in the future (see [here](https://github.com/tektoncd/pipeline/pull/1773#issuecomment-568018607))
