### ISSUE TITLE
'Tekton: Load' command for PipelineRuns, TaskRuns, CluseterTask, PipelineResource and task.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-tekton#102]
'Load' command should able to open yaml file in text editor.

**Comment by siamaksade** [comment]
@sudhirverma this is already fixed right?

**Comment by sudhirverma** [comment]
The load command is provided in vscode-kubernetes extension and I am thinking to implement the load command in this extension too.

**Comment by siamaksade** [comment]
I see. You mean in the Tekton Pipelines view

**Comment by sudhirverma** [comment]
closing this issue, Fixed in #111
