### ISSUE TITLE
Update tkn version to 0.6

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#103]
The Tekton extensions looks for `tkn` v0.3. It should be updated to latest which is 0.6 right now

**Comment by siamaksade** [comment]
Does the extension need to lock a particular version of the CLI, instead of a range e.g. 0.6+?

**Comment by sudhirverma** [comment]
In the latest master, we are supporting the `tkn version: 0.5.1`, we are working on migrating the `tkn version: 0.6`

**Comment by siamaksade** [comment]
@sudhirverma  What's the reason for pinning the tkn version as opposed to 0.5.1+?

**Comment by evidolob** [comment]
We need to detect if user has newer version of `tkn` cli, and do not prompt to download old wan, just show warning message that user has newer version and extension may not work 100% correctly.

**Comment by evidolob** [comment]
@siamaksade Am I correct?

**Comment by sudhirverma** [comment]
we can create a new issue for this

**Comment by evidolob** [comment]
OK, @sudhirverma can you create?

**Comment by sudhirverma** [comment]
okay I will create a new issue

**Comment by evidolob** [comment]
https://github.com/redhat-developer/vscode-tekton/issues/116
