### ISSUE TITLE
Add task ref snippet when editing pipelines

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#112]
Aftring generating a YAML skeleton for a Pipeline, it would be useful if the extension assist the user to generate task reference snippets to add to the `tasks` attribute of the pipeline, based on the `Task`s that are installed in the namespace and the `ClusterTasks` that are available on the cluster. 

Similar capability is available in the web console based on an extension CR:
https://github.com/openshift/tektoncd-pipeline-operator/pull/127/files

**Comment by evidolob** [comment]
Fixed with https://github.com/redhat-developer/vscode-tekton/pull/138
