### ISSUE TITLE
Allow to use Tekton Catalog for creating and editing tekton related resources

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-tekton#121]
The extension has only basic support for creating tekton related resources from the beginning based on snippets. Developers should have access to existing tasks form various catalogs through vscode UI like:
* Catalog(s) view
* yaml editor content assist 

Repo for Tekton's experimental components https://github.com/tektoncd/experimental which includes, I assume, catalogs folder contains support for Tekton CLI tool.

**Comment by vdemeester** [comment]
@dgolovin yes, the https://github.com/tektoncd/experimental/tree/master/catalogs folder should hold the serverside and cli components of this experiment, that could/should be usable in the extension :angel:

**Comment by evidolob** [comment]
Editing Tekton Pipeline can be done in two ways:

1. Graphical editor (webview based).
2. Text editor, can reuse `yaml-language-sever` to provide traditional code editing features like IntelliSense and code validation.

We need to decide what experience we want to provide to end user. Each way has own pros and cons, in terms of implementation, text editor is mach simpler but graphical easy to use for end user.

@siamaksade @gorkem WDYT?

**Comment by siamaksade** [comment]
@evidolob (2) text editor content assistance is more important IMO

**Comment by evidolob** [comment]
OK, I agree(but I developer so I like editing text/code more than visual/graphical editor).
For now ` https://github.com/tektoncd/experimental/tree/master/catalogs` has only placeholder code and I cannot do match there, so my plan is start with improve editing of pipeline yaml:

- code completion proposals for existing/deployed tasks from cluster and namespace tasks 
- code completion proposals for task configuration(`params` and `resources `)
- validation tool which validate that task has proper configuration and provide `Diagnostics`  for editor
- provide code actions for error/warning correcting actions.

@siamaksade Is this good for you?

**Comment by siamaksade** [comment]
@evidolob it does. and it's matching what the dev console is going to do while experimental/catalog makes progress. dev console also looks at task/clustertasks that are already installed on the cluster
