### ISSUE TITLE
Developer's view of pipeline

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/vscode-tekton#122]
This is pretty random and perhaps better left for a separate extension, but as an average developer I spend brief periods working directly and intensely on a build - setting it up, debugging it, etc, i.e. the kind of thing this extension handles - and most of my time developing code and submitting PRs - where I only care about the status of a few particular builds that I'm doing active development on.

It would be handy to have a 'developers mode' or simple separate view that only focussed on the status of a few particular builds (e.g. master + current branch/PR) and had links to build output and dashboard, or the output of failed builds.

**Comment by gorkem** [comment]
Would having filtering on the current view work for this?

**Comment by siamaksade** [comment]
Relates to https://github.com/redhat-developer/vscode-tekton/issues/82

**Comment by evidolob** [comment]
@deboer-tim Can you look on https://github.com/redhat-developer/vscode-tekton/pull/144

**Comment by evidolob** [comment]
Fix with #82
