### ISSUE TITLE
Update CLI not found error message

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#130]
The current error message when the Tekton CLI is not found is: 
```
Cannot find A CLI for interacting with Tekton v0.6.0.
```

Tekton v0.6.0 is in correct given that 0.6.0 is the version of the CLI. It should possibly say instead:
```
Cannot find Tekton CLI v0.6.0 for interacting with Tekton Pipelines. 
```

**Comment by evidolob** [comment]
We need to handle that by changing regexp https://github.com/redhat-developer/vscode-tekton/blob/0babd127ab25cbb4a6efd6283d30956a8fe064f1/src/tools.ts#L124 to have optional `v` before version.
https://github.com/tektoncd/cli/issues/604

**Comment by siamaksade** [comment]
This is just about the wording of the error message. Tekton CLI v0.6.0 vs Tekton 0.9

**Comment by evidolob** [comment]
Yes, sorry. Message fixed with this commit https://github.com/redhat-developer/vscode-tekton/commit/8bb4883d915d0ae6bac090978e963f2a32613d2c
