### ISSUE TITLE
Refreshing pipelines view gives undefined property error  

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#135]
When a pipeline is started via the extension, after refreshing the pipelines view an error is displayed that a property cannot be ready because it's undefined:

<img width="1098" alt="Screenshot 2020-01-16 at 10 49 01" src="https://user-images.githubusercontent.com/1174934/72539870-00306e80-384e-11ea-949b-3c3fef9fbfbf.png">

**Comment by sudhirverma** [comment]
@siamaksade I have started the pipeline, and when I am clicking on the refresh button it doesn't throw any error. Are you still facing the issue after clicking on the refresh button while starting the pipeline.

**Comment by siamaksade** [comment]
I do. What version of Pipelines Operator and CLI do you have? I get it with Operator 0.9 and CLI 0.6

**Comment by sudhirverma** [comment]
I am using VSCode version: 1.41.1, CLI: 0.6.0 and OpenShift Pipelines Operator: 0.9.1. What version of VSCode are you using?

**Comment by siamaksade** [comment]
@sudhirverma also 1.41.1. Is there any cache I should remove on my side to reset?

**Comment by sudhirverma** [comment]
what is the log are you getting in the `output channel -> Tekton Pipelines` while clicking on the refresh button.

**Comment by siamaksade** [comment]
It doesn't come up anymore in my env either. You can close this and I'll re-open if it reappears again
