### ISSUE TITLE
Add support for trigger resource types

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#147]
[Tekton Triggers](https://github.com/tektoncd/triggers) enable creating webhooks for pipelines and include the following CRs:
* `TriggerTemplate`
* `TriggerBinding`
* `ClusterTriggerBinding`
* `EventListener`

The trigger CRD should be displayed in the Tekton window

**Comment by sudhirverma** [comment]
@siamaksade we generally show icon for tree view. It would be good if we get the icon for 
`TriggerTemplates`, `TriggerBinding`, `EventListener`.

for now, I am using the Pipeline icon for trigger resource. 

<img width="432" alt="Screenshot 2020-02-25 at 6 22 11 PM" src="https://user-images.githubusercontent.com/9924513/75249421-4dfca700-57fc-11ea-9df1-6e8d1dba56bd.png">

let us know who is the best person to reach out for the icon.

**Comment by sudhirverma** [comment]
for now, tkn doesn't provide any command to list  ClusterTriggerBinding. I have created an issue https://github.com/tektoncd/cli/issues/752 on tkn side. when they will resolve the ClusterTriggerBinding feature then I will implement the feature on vscode side.
