### ISSUE TITLE
Show selected resources as a tree

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#171]
When select resources to be displayed in the separate window, the result should show as a tree which deduplicates resources that are already displayed.

Currently selecting the following:
<img width="384" alt="Screenshot 2020-03-03 at 11 12 46" src="https://user-images.githubusercontent.com/1174934/75795182-f3a1a000-5d3f-11ea-805c-9cc9f23654f3.png">

Results in:
<img width="353" alt="Screenshot 2020-03-03 at 11 12 52" src="https://user-images.githubusercontent.com/1174934/75795179-f3090980-5d3f-11ea-8925-d47cc178ceea.png">

The resources are displayed twice. The expected result is:
```
PipelineResources
    - petclinic-git
    - petclinic-image
```

Selecting only `petclinic-git` should result it in:
```
PipelineResources
    - petclinic-git
```

**Comment by evidolob** [comment]
@siamaksade And what if selected resource in deeper level:
```
Pipelines
   - somePipeline
      - somePipelineRun1 <- selected
      - somePipelineRun2
```

Should result be:
```
Pipelines
   - somePipeline
      - somePipelineRun1
```
?

**Comment by siamaksade** [comment]
Yes. The result should show the parents all the way to the root
