### ISSUE TITLE
Update snippet apiversions

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-tekton#176]
Update the `apiVersion` for the snippets to `tekton.dev/v1beta1`.

**Comment by evidolob** [comment]
@gorkem @siamaksade 
I try to deploy this [task](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/taskruns/task-result.yaml) 
form `tektoncd`  examples/v1beta1 directory and it doesn't work on my tekton installed with "OpenShift Pipelines Operator"  `0.10.7` on CRC.
I got error:
```
error: unable to recognize "https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/v1beta1/taskruns/task-result.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1"
```
I'm not sure that I not brake user if I change snippets.

**Comment by evidolob** [comment]
Resolved with https://github.com/redhat-developer/vscode-tekton/pull/245
