### ISSUE TITLE
Add PipelineRun in the tree as a root node

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#197]
PipelineRuns can be standalone without referencing a pipeline and should be displayed in their own folder, in addition to under a particular pipeline

**Comment by gorkem** [comment]
There can be too many `PipelineRuns` without a way to group them together that folder can get very crowded. Should we have a folder for orphan `PipelineRuns` only?

**Comment by siamaksade** [comment]
@gorkem `PipelineRun` and `TaskRun` can embed the pipeline and task using `pipelineSpec` and `taskSpec`. Those won't show up anywhere. 

Limiting the number of items (https://github.com/redhat-developer/vscode-tekton/pull/127) should apply here as well to address the too many items problem.
