### ISSUE TITLE
Show resource YAML on double-click

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#224]
Currently the resource YAML shows on clicks. It should be displayed on double-click so user can click on resources for actions without opening the YAML.

Alternatively add an action in the context menu to open the YAML

**Comment by evidolob** [comment]
We also can consider use "inline" action to open tekton resource in editor: https://code.visualstudio.com/api/extension-guides/tree-view#view-actions 
Example:
<img width="374" alt="Screenshot 2020-04-02 at 09 24 38" src="https://user-images.githubusercontent.com/929743/78217030-d2a9a780-74c3-11ea-941a-1c72c66e853e.png">
