### ISSUE TITLE
Resource names should be capitalised 

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#28]
Resource names should be capitalised to `TastRun`, `PipelineRun`, etc.

<img width="316" alt="Screenshot 2019-08-14 at 16 26 56" src="https://user-images.githubusercontent.com/1174934/63029155-5a4c9280-beb0-11e9-99c9-2cfa5e733e98.png">

**Comment by onyiny-ang** [comment]
This is fixed in #29. Also, this alerted me to the end of [this line](https://github.com/redhat-developer/vscode-tekton/blob/master/src/extension.ts#L64) which is very wrong :joy_cat: So thank you!
