### ISSUE TITLE
Provide way to switch project/namespace or display project/namespace.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-tekton#287]
currently, it difficult to understand tekton resources belong to which project/namespace.

We should provide a way to display the project/namespace in vscode-tekon.

If possible we should also provide the way to switch the project from vscode-tekton.

**Comment by siamaksade** [comment]
This would be very helpful also combined with more consistency across Kubernetes, OpenShift and Tekton extensions kubeconfig.

**Comment by gorkem** [comment]
Take a look at https://github.com/Azure/vscode-kubernetes-tools/issues/757

**Comment by gorkem** [comment]
Please coordinate with @lstocchi about implementing this. Ideally we would have this on the `vscode-kubernetes-tools` I think there is an agreed way on that plugin to implement it similar to git branch switches.

**Comment by siamaksade** [comment]
Let's hold on with switch namespaces and only display the namespace as the first node in the tree (same level as the rest of the nodes).

**Comment by siamaksade** [comment]
Merged on k8s extension
