### ISSUE TITLE
Tekton.edit error when clicking on the "Open in Editor" icon

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#296]
i get this error 
![image](https://user-images.githubusercontent.com/49404737/82552068-b809bb80-9b61-11ea-8089-b63a32653d4b.png)

when clicking on any of the `Open in Editor` icon you find on the right of a tree item
![image](https://user-images.githubusercontent.com/49404737/82552111-c8ba3180-9b61-11ea-934d-e562a7722cde.png)

By clicking on the name of the resource works fine so it's just the icon

**Comment by evidolob** [comment]
That strange, I use that command every day and never see that error, can you provide additional information?

**Comment by lstocchi** [comment]
@evidolob I made some test and found out that if the `server connector` extension is installed i get this error, otherwise it works fine. It would be great if you could install https://marketplace.visualstudio.com/items?itemName=redhat.vscode-server-connector and try to replicate it.

**Comment by evidolob** [comment]
I install `server connector` and `Open in Editor` still works. 
Error that you describe is very strange, that can happen only in if tekton extension is not register handler for

**Comment by lstocchi** [comment]
What if you uninstall tekton extenstion and then reinstall tekton (with the server connector already installed)? Still works fine for you? 

BTW yeah it's very strange.

**Comment by evidolob** [comment]
I usually don't have tecton extension installed, I use it from dev mode. But for your ask, I test both cases, first install  server connector then run dev mode with tekton extension - all work. Then install tekton extension from marketplace and test then all work also.

**Comment by evidolob** [comment]
Btw, I don't have any server running/installed for server connector, maybe that the case?

**Comment by lstocchi** [comment]
I looked in the `Log (Extension Host)`. Nothing wrong apparently. 
I don't know what is the issue, i'll keep investigating and let you know if i discover something. 

I don't think it is related to having any server installed. I don't start any rsp server. Just open vscode, go to the tekton tab and click on "open in editor" icon of some random resource. No idea seriously.

**Comment by lstocchi** [comment]
Closing this for the moment and i'll reopen it if i have some more info. Thanks @evidolob

**Comment by sudhirverma** [comment]
I also install `server connector` and start server but not getting an error while opening the editor from the icon.

**Comment by lstocchi** [comment]
I had some time to look into this and i found something. There are still some aspects which i need to clarify like "why did it work when i remove server connector?". Maybe i was playing with intellij or i was on Windows, i don't remember but i'll keep investigating.

BTW back to the issue. If i remove tekton from the path the extension use (in my case ~/.vs-tekton/tkn), it will ask me if i want to download and install it 
![image](https://user-images.githubusercontent.com/49404737/83140083-c457c080-a0ed-11ea-832b-140c781b32c1.png)

The problem is that the code is stuck on this popup and it doesn't register any command.
```
response = await vscode.window.showInformationMessage(
            `Cannot find Tekton CLI ${ToolsConfig.tool['tkn'].versionRangeLabel} for interacting with Tekton Pipelines.`, installRequest, 'Help', 'Cancel');
```

but i can correctly see and navigate the tree
![image](https://user-images.githubusercontent.com/49404737/83140314-2d3f3880-a0ee-11ea-95c7-5c633502d934.png)

so if i try to execute any command (in my case opening the config of a resource), i get the error message 
![image](https://user-images.githubusercontent.com/49404737/83140376-45af5300-a0ee-11ea-9b06-881ff9f59336.png)
