### ISSUE TITLE
Doubleclick should open yaml in Editor

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/vscode-tekton#303]
When I  double click on resource/TaskRun/TaskResource....it should open resource/yaml in editor by default in Tekton Pipelines view. Right now when I double click on something it does nothing.

**Comment by evidolob** [comment]
Unfortunately VSCode does't provide API for extension to add double click handler to tree item.
And in general VSCode  doesn't use double click at all. 
In first implementation we open resource on click, but it was not very comfortable to navigate thru tekton tree, as each click on item opens that resource in editor, so we decide to add inline icon, click on which opens resource.

**Comment by evidolob** [comment]
VS Code doesn't allow us to customise the double-click behaviour.
https://github.com/microsoft/vscode/issues/39601
