### ISSUE TITLE
TaskRun and PipelineRun success status is ambiguous 

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#333]
The color used for a TaskRun and PipelineRun that has successfully executed is the same as a Pipeline and Task which makes it somewhat vague if green is associated with successful runs.

**Comment by evidolob** [comment]
@siamaksade I'm not sure what we need to change? We need to have other icon color for success status of TaskRun and PipelineRun?

**Comment by siamaksade** [comment]
The coloring might not be sufficient. There are 2 types of resources in Tekton:
A) Without status (pipeline, task, pipeline resource, etc): green
B) With status (pipelinerun, taskrun): green=success, red=failed

So seeing a green icon doesn't visually give any cues:
<img width="192" alt="Screenshot 2020-06-24 at 19 10 21" src="https://user-images.githubusercontent.com/1174934/85601123-610a7100-b64e-11ea-86a6-54264597b9e2.png">

Would it make sense to augment the green icon with the status symbols?
<img width="192" alt="Screenshot 2020-06-24 at 19 10 21" src="https://user-images.githubusercontent.com/1174934/85602225-7633cf80-b64f-11ea-9e25-3b9d3b19f316.png">
<img width="192" alt="Screenshot 2020-06-24 at 19 10 21 copy" src="https://user-images.githubusercontent.com/1174934/85602231-76cc6600-b64f-11ea-8b3a-87a1d891c9ea.png">

**Comment by sudhirverma** [comment]
Closing this issue.
