### ISSUE TITLE
runAfter code completion adds "null" as name

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#340]
The code completion for `runAfter` adds `null` as the name of the task:

<img width="290" alt="Screenshot 2020-07-09 at 14 10 57" src="https://user-images.githubusercontent.com/1174934/87038530-2aa42880-c1ee-11ea-9d3a-20671f81ed3d.png">

It should be either an empty string or something like "taskName"

**Comment by evidolob** [comment]
Fixed with https://github.com/redhat-developer/yaml-language-server/pull/277
