### ISSUE TITLE
Search tasks in Tekton Hub

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#346]
Tekton Hub provides an API for searching for tasks and retrieving their details as well as installing them on the cluster. As a Tekton user, it would be valuable to be able to search for tasks directly in VS Code, see their details and install them on the cluster.

**Comment by siamaksade** [comment]
One way would be to add it to the command palette to be able to search for tasks, and open details page (similar to extension details pages) and install from there.

**Comment by evidolob** [comment]
We can use https://code.visualstudio.com/updates/v1_50#_webview-views to integrate TektonHub

**Comment by evidolob** [comment]
We have agreement to use new webview api, to implement TektonHub integration, UI should be similar to VSCode extension panel, with ability to select version for task and preview of task/readme when user click on task.
