### ISSUE TITLE
Install Tekton on the cluster

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#356]
Add an action to be able to install Tekton on a cluster which doesn't have Tekton installed. 

**Kubernetes:**
https://github.com/tektoncd/pipeline/blob/master/docs/install.md
https://github.com/tektoncd/triggers/blob/master/docs/install.md

**OpenShift:** 
Installing the OpenShift Pipelines Operator from the OperatorHub

**Comment by mohitsuman** [comment]
@sudhirverma Please refer the screenshot of the welcome page to understand the workflow.

**Comment by sudhirverma** [comment]
@mohitsuman and @evidolob we already show the welcome page to install the pipeline and I have added the `Tekton Trigger` button to open the documentation for the trigger.

<img width="481" alt="Screenshot 2021-06-23 at 3 16 50 PM" src="https://user-images.githubusercontent.com/9924513/123075788-29d3c900-d436-11eb-8390-03f26370648f.png">
