### ISSUE TITLE
Unique names for files from Open in Editor 

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#362]
When opening a Tekton resource in the editor through "Open in Editor" action, the file names might appear confusing since they look like files form the user's workspace.

In the following example, `petclinic-pipeline.yaml` is a file in my workspace and `petclinic-deploy.yaml` is the Tekton resource that is live on the cluster:

<img width="754" alt="Screenshot 2020-07-13 at 16 21 30" src="https://user-images.githubusercontent.com/1174934/87315766-1c734680-c525-11ea-8002-ef9439725f46.png">

It would be useful to distinguish the live resource file names e.g. appending a random string in the end.

**Comment by siamaksade** [comment]
One alternative would be to add a unique suffix to the name so that it differentiates from the files in my workspace

**Comment by sudhirverma** [comment]
Hi @siamaksade I have open a file from the local filesystem and other from tekton tree with the same name and you can see in the image after the file name it show the path of the file.

<img width="716" alt="Screenshot 2020-09-23 at 4 16 35 PM" src="https://user-images.githubusercontent.com/9924513/94011071-71082d00-fdc4-11ea-9407-57f95d8f6cd2.png">

**Comment by siamaksade** [comment]
Should we show the path in the full path format instead? For example `/tmp/.../build-an-deploy.yaml`

**Comment by evidolob** [comment]
@siamaksade Unfortunately we cannot control that, that is the feature of vscode, and vscode do not provide API for that

**Comment by siamaksade** [comment]
We should show perhaps something else then that makes it clear that these objects are from the cluster. Name of the cluster perhaps? Anything else that we could add?

**Comment by evidolob** [comment]
Hm, we can add cluster name as prefix for file name: `/some/path/clustername-file-name.yaml` so in editor tab will be only `clustername-file-name.yaml`

**Comment by siamaksade** [comment]
That sounds better

**Comment by evidolob** [comment]
@sudhirverma Are you OK with this?

**Comment by sudhirverma** [comment]
@evidolob  and @siamaksade I can add the cluster name before the file name but it will be too long name for the file.

for ex: 

for me cluster name is `api-sudhir-cluster-19-a0b1-p1-openshiftapps-com:6443` if I add `clustername-file-name.yaml` it will too long name for file.
