### ISSUE TITLE
TaskRuns list does not auto refresh

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#365]
When creating a new TaskRun via YAML, the tree does not automatically refresh to show the TaskRun under the Tasks.

**Comment by sudhirverma** [comment]
@siamaksade are you using tekton extensions command to create new taskRun vai Yaml like `Deploy on save` ?

**Comment by siamaksade** [comment]
This should happen for all Tekton resources if the node in the tree is open.
