### ISSUE TITLE
Default param values missing in start 

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#386]
When starting a pipeline via the new wizard, the default pipeline params are not displayed. Furthermore, the text fields contain `Name` as the value:

<img width="506" alt="Screenshot 2020-08-07 at 17 35 11" src="https://user-images.githubusercontent.com/1174934/89662503-796bdd80-d8d4-11ea-981f-3618f6fdb7ee.png">

<img width="471" alt="Screenshot 2020-08-07 at 17 35 25" src="https://user-images.githubusercontent.com/1174934/89662512-7cff6480-d8d4-11ea-85c0-7b11670e228b.png">

**Comment by sudhirverma** [comment]
> When starting a pipeline via the new wizard, the default pipeline params are not displayed. Furthermore, the text fields contain `Name` as the value:
> 

`Name` is not the value it is a placeholder for the input field. If YAML has a default value for param then I will show the default value in the input field.
