### ISSUE TITLE
Cancel button on finished pipeline

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/vscode-tekton#444]
I have used tutorial from https://github.com/openshift/pipelines-tutorial#deploy-sample-application.

When the pipeline finished, there was still cancel button on this pipeline:
![image](https://user-images.githubusercontent.com/17871936/98239169-d7f23780-1f67-11eb-890e-7b262eafafc9.png)

I suppose the cancel button should disappear, when the pipeline finished.

**Comment by siamaksade** [comment]
We need a spike on how to make the menu context-aware.
