### ISSUE TITLE
WSL: failure to find the tkn binary

### ISSUE THREAD

**Issue by chmouel** [redhat-developer/vscode-tekton#454]
I am running a vscode window inside from Windows 10 on WSL, and i am getting a "Please install the openshift pipelines Operator", which i guess it means the extension cannot find the `tkn` binary ?

![image](https://user-images.githubusercontent.com/98980/99406528-4632e480-28ee-11eb-9428-53bda00313b9.png)

The tkn binary is installed in a ubuntu WSL via the official tektoncd cli package : 

```
chmouel@thebond 🐱 ~% dpkg -l tektoncd-cli|tee                                                                                                                                KIND
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-====================================================
ii  tektoncd-cli   0.14.0-0     amd64        A command line interface for interacting with Tekton
chmouel@thebond 🐱 ~% which tkn                                                                                                                                               KIND
/usr/bin/tkn

```

**Comment by evidolob** [comment]
@chmouel Can you check that `tkn` has access to cluster, `tkn version` should be enough

**Comment by evidolob** [comment]
> i am getting a "Please install the openshift pipelines Operator", which i guess it means the extension cannot find the tkn binary
No, that means that we cannot detect that you have Tekton Pipelines installed.

**Comment by chmouel** [comment]
seems like it 

![image](https://user-images.githubusercontent.com/98980/99410897-497c9f00-28f3-11eb-8197-5ea2d7114462.png)

**Comment by evidolob** [comment]
OK, that means that problem somewhere in the way how we use `tkn`

**Comment by chmouel** [comment]
Oh i think it was some error from my part, if i start the wsl "vm" before, load up the kube/config to connect properly and then run the extension it woudl then work!

![image](https://user-images.githubusercontent.com/98980/99411462-ea6b5a00-28f3-11eb-8347-1969fe46512c.png)


I think it's more a user issue, and probably should not need a fix from you...
