### ISSUE TITLE
Find references of tasks inside the cluster

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#487]
It may happen that you have many tasks on the cluster and you are afraid to edit/delete one of them because you don't know where they are actually used. One useful thing could be to add an action to find existing references of a task.
This can also be extended to other resources. Is X used somewhere?

**Comment by siamaksade** [comment]
Same for ClusterTasks

**Comment by sudhirverma** [comment]
@lstocchi, @siamaksade, and @evidolob 

I was thinking If we are deleting the task or ClusterTasks which are being used in pipeline/pipelineRun/taskRun then I will show the warning to the user that it can affect the pipeline and I will delete the taskRun also which are being referred to that Task/ClusterTask. WDYT?


Another question if we are deleting pipeline should I delete the pipelineRun and TaskRun which are being referred to that pipeline?

**Comment by lstocchi** [comment]
@sudhirverma in IJ we already have something similar. When a user tries to delete a pipeline or task, we ask if she also wants to delete its related resources. If the checkbox is checked everything is deleted (img below).
![image](https://user-images.githubusercontent.com/49404737/111356272-803ba980-8688-11eb-8f0a-9c5315e1cd67.png)

The idea to show a warning during deletion is good for me but I don't think if it fully covers everything. 
If a task is used somewhere you should also show the warning if that task is being edited (during saving). Other point is, are you going to show the list of pipelines where that task is used? Because the warning is useful but if it doesn't tell me where the task is actually used it may lead to errors. Let's say i have task A used in pipeline B and C (but i'm only aware of pipeline B), when i see the warning i could  click  on `OK` (because i'm erroneously sure it is only used in pipeline B) and i could accidentally change the behavior of another pipeline without knowing it. To keep it simple maybe we could just create an action that show a list of pipelines  where the task is used? 

Probably i think too much and it's highly likely this stuff will only be used by insane ppl like me so let's wait for @siamak's answer , maybe he can tell us how customers want this to work.
