### ISSUE TITLE
telemetry support for tektonHub.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-tekton#524]
Telemetry support for tektonHub when the user clicks on install, uninstall button.

**Comment by lstocchi** [comment]
Do you just collect infos like "user clicked the install/uninstall button" or you also save the name of the tektonhub's task installed/uninstalled (in clear)?

**Comment by sudhirverma** [comment]
> Do you just collect infos like "user clicked the install/uninstall button" or you also save the name of the tektonhub's task installed/uninstalled (in clear)? Just to know because i have this doubt for the IJ plugin, not sure if you already discussed it with Siamak/Fred. As their name are not created by users do they need to be anonymized as well for the privacy?

I was thinking to collect info like 'user clicked on install/uninstall button' but we can ask @siamaksade, @evidolob, and @fbricon what's their opinion on collecting the name of the tektonHub' task for telemetry while the user click on install/uninstall button.
