### ISSUE TITLE
Do we required tkn cli command to start pipeline?

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-tekton#528]
As we have two methods to start pipeline from YAML data and tkn cli start command it would be good to use one method to start the pipeline. As VolumeClaimTemplates is not supported in tkn cli start command.

cc: @siamaksade and @evidolob

**Comment by lstocchi** [comment]
@sudhirverma I found this https://github.com/tektoncd/cli/pull/1066. Doesn't the tkn cli start command work with VolumeClaimTemplates or you missed this patch? I still didn't test it, just wanted to know if you have more info on it before to start adding VolumeClaimTemplates support in IJ Tekton.

**Comment by sudhirverma** [comment]
In pipeline start documentation https://github.com/tektoncd/cli/blob/main/docs/cmd/tkn_pipeline_start.md they have not provided the information about `VolumeClaimTemplates`, If they provide support for `VolumeClaimTemplates ` in tkn start command. Then I will use only tkn command to start the pipeline.

**Comment by lstocchi** [comment]
Ah ok, got it. Either they forgot to update the readme or this thing doesn't work at all (maybe it was deleted in a later PR??). I'll test it as well for IJ :+1:
