### ISSUE TITLE
Unable to delete Task

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/vscode-tekton#536]
When I execute delete command on any Task under `Tasks` tree I got:

```
Error running command tekton.explorerView.delete: Running the contributed command: 'tekton.explorerView.delete' failed.. This is likely caused by the extension that contributes tekton.explorerView.delete.
```
This it blocker for `0.13.0` release.

**Comment by sudhirverma** [comment]
I have tried to delete Task under `Tasks` in tree view but did not get any error.

**Comment by evidolob** [comment]
You need to have pipeline with `taskSpec` instead of `taskRef` inside of one task
