### ISSUE TITLE
Create 'New Pipeline Resource' command

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-tekton#55]
Currently the only way to create resource is to use `oc` or `kubectl` tools form command line, there should be command to do that from context menu on `Pipeline Resources` node and command palette. 
New Git resource workflow should let you select from repositories presented in workspace.
New Image resource workflow should let you slect form ImageStreams presented in cluster.

**Comment by sudhirverma** [comment]
https://github.com/tektoncd/cli/issues/560
