### ISSUE TITLE
Unable to delete pipelinerun

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#579]
I tried to delete a pipelinerun and even if the success message was displayed nothing was actually done.
![image](https://user-images.githubusercontent.com/49404737/118295441-27e42500-b4dc-11eb-9450-09a2fe18641a.png)

**Comment by sudhirverma** [comment]
I think I have fixed this in https://github.com/redhat-developer/vscode-tekton/pull/559 PR I will check and update the pr.
