### ISSUE TITLE
Additional telemetry 

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#583]
* If user has oc and kubectl installed
* Kubernetes version
* OpenShift version

**Comment by sudhirverma** [comment]
@mohitsuman  can we use `oc` to check Kubernetes and OpenShift version as we need `oc command` to check OpenShift version.

**Comment by mohitsuman** [comment]
@sudhirverma yes the oc command should be ideal. I cans see the PR does the same.
