### ISSUE TITLE
Add support to install pipelines from Hub

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#610]
It looks like the Hub also contains pipelines now. We should add support for them as well.
I made a test with `build-push-gke-deploy` pipeline
Current behavior 
![image](https://user-images.githubusercontent.com/49404737/125933759-3e8f1c36-3fda-47c8-9e10-bf8c0462f6be.png)

When trying to install it 
![image](https://user-images.githubusercontent.com/49404737/125933844-4aa475d3-2f30-4251-990d-c928c63c2b55.png)

**Comment by mohitsuman** [comment]
@lstocchi Which version of tkn did you test the `build-push-gke-deploy` pipeline ? As 0.21.0 is the latest tkn cli.

**Comment by lstocchi** [comment]
I don't remember the version but i don't use tkn hub to save it on the cluster. I only use tkn hub to get it `tkn hub get pipeline ...`

**Comment by evidolob** [comment]
Hm, that should work. Thx @lstocchi! 
I will provide PR tomorrow.
