### ISSUE TITLE
Add action for fetching diagnostic data

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#622]
In IJ we have an action that fetches data from k8s resources (pods, statefulsets) when a taskrun/pipelineruns fails and tkn cli doesn't provide much infos (e.g a pvc available to create a pvc). It should be good to have the same in vscode

**Comment by sudhirverma** [comment]
@mohitsuman  Fixed in https://github.com/redhat-developer/vscode-tekton/issues/418

**Comment by mohitsuman** [comment]
@sudhirverma I was looking for the gif just to review and close this. can you add the gif here ?

**Comment by sudhirverma** [comment]
![dig](https://user-images.githubusercontent.com/9924513/141826797-b767141f-d17f-408b-81a8-3d59ed04f938.gif)

**Comment by mohitsuman** [comment]
Thanks for the update @sudhirverma . I am closing the issue.
