### ISSUE TITLE
Cannot access tekton hub

### ISSUE THREAD

**Issue by vbkgithub** [redhat-developer/vscode-tekton#629]
**Environment**
VS Code version: 1.60.2
OS: win32
Extension version: 0.18.0

**Description**
When I try to access tekton using vscode extension. I see an error message. Please see attached screenshot
![image](https://user-images.githubusercontent.com/3975768/135900562-49d5ff39-89d0-4bb3-9863-54d58d5414e8.png)

**Comment by evidolob** [comment]
That is VS Code issue https://github.com/microsoft/vscode/issues/134244 
It should be fixed with new VS Code release

**Comment by ilan-pinto** [comment]
Same here
