### ISSUE TITLE
Certificate expired for TektonHub

### ISSUE THREAD

**Issue by eirisdg** [redhat-developer/vscode-tekton#662]
**Environment**
VS Code version: 1.63.2
OS: linux
Extension version: 1.0.1

**Description**
TektonHub shows Error: certificate has expired

![image](https://user-images.githubusercontent.com/5367659/148533609-efe99135-137e-497f-8f4c-75837408a4c6.png)

**Comment by hightechrdn** [comment]
Good day. After installing the Tekton Pipelines extension of the first time, I am seeing the same "Error: certificate has expired" message and cannot search for Tektonhub resources. I am connecting to an OpenShift 4.9.10 cluster. I have code-1.63.2-1639562596.el7.x86_64 installed on Fedora 34.

**Environment**
VS Code version: 1.63.2
OS: linux
Extension version: 1.0.1

**Comment by sudhirverma** [comment]
That is VS Code issue https://github.com/microsoft/vscode/issues/136787 

As a workaround, it seems to work if the user sets this option in user settings in VSCode

`"http.systemCertificates": false,`

**Comment by mohitsuman** [comment]
This issue should be fixed with VSCode 1.66 version. @eirisdg can you please try using the extension and see if it works as expected for you.
