### ISSUE TITLE
The Extension does not list any tasks in the tekton hub search.

### ISSUE THREAD

**Issue by flokain** [redhat-developer/vscode-tekton#678]
**Environment**
VS Code version: 1.65.2
OS: linux
Extension version: 1.0.1

**Description**
The Extension does not list any tasks in the search. (internet is accessible
![image](https://user-images.githubusercontent.com/14279221/160211443-9b3a4b24-b8d3-484e-a009-64899b9d793a.png)

**Comment by mohitsuman** [comment]
@sudhirverma can you please replicate the issue exists for the latest workflow.

**Comment by sudhirverma** [comment]
@flokain I have tried on Linux I was able to see the list of tasks in tekton hub.

![tektonhub](https://user-images.githubusercontent.com/9924513/204031453-77feddfd-811b-4fa5-b035-b2ebb8020aea.png)

**Comment by mohitsuman** [comment]
Please check The new release of the extension and let us know. Feel free to reopen if the issue still persists.
