### ISSUE TITLE
Extension extremely slow when running with Ocp sandbox

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#729]
I'm opening this issue just to share my findings. Maybe someone will find it helpful when using the search bar.
Or we could update the doc mentioning it.

When I start the extension on ocp sandbox it takes a lot to load. After investigating a bit it looks like my old kubectl version causes it. 
Kubectl 1.22
![image](https://user-images.githubusercontent.com/49404737/210389931-1afd2397-3843-4890-b904-164f7ef04ab9.png)

Kubectl 1.26
![image](https://user-images.githubusercontent.com/49404737/210389986-b44364f8-6317-436d-b641-bb068c370266.png)

Solution - use an updated version of kubectl.

**Comment by lstocchi** [comment]
@mohitsuman related to this... I was thinking why we have a specified version range here for kubectl https://github.com/redhat-developer/vscode-tekton/blob/main/src/tools.json#L7

What's the point? For the tkn cli we always target the latest release as we assume users want to use the latest operator but for kubectl this is not true. I could use an older cluster with the latest operator. 
And what's the point of checking the version range if the user can face a similar issue as above? Or we download/ask the user to use a kubectl version in line with the cluster version or having those static numbers have no sense. WDYT?

**Comment by mohitsuman** [comment]
I think the idea is to have the kubectl version in the first place to make sure we support the latest release, in sync with the security fixes (CVEs if any). I agree we do not need version range check anymore as the specific version makes more sense.

We can remove the version range check accordingly.
