### ISSUE TITLE
Limit number of pipelineruns and taskruns shown in tree through extension preference

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-tekton#79]
Would be good to have limit, because list can grow over time.

**Comment by jeffmaury** [comment]
Something I have in mind for the IntelliJ plugin: display the first n (5 ?) elements and if there are more, add a clickable More node after the last one. When click display the next n ones. But not sure tkn allows this kind of cursor mode. Maybe @joshuawilson can comment

**Comment by dgolovin** [comment]
@jeffmaury there is no cursor mode, just limit for how many records to fetch. It still possible to the way you suggested, but it would require reload whole node with increased --limit option.

**Comment by joshuawilson** [comment]
What if you fetch more then you need, say 100. Then you display the first 5 or 10. There could be a `more` button or something that would display another 5 or 10. If you get to 70, then fetch another 100. 

That is basic pagination.

**Comment by jeffmaury** [comment]
The issue here is that the tkn client does not support pagination but only result limiting
