### ISSUE TITLE
Error: stdout maxBuffer lenght exceeded

### ISSUE THREAD

**Issue by vdemeester** [redhat-developer/vscode-tekton#90]
On a cluster with a few pipelines and a whole lot of taskrun, I'm running into the following issue. It still loads the pipelines but…

![2019-11-25_18-30-51](https://user-images.githubusercontent.com/6508/69563682-dc6d4c80-0fb1-11ea-9ab7-f63ec153d10b.png)

/kind bug

**Comment by dgolovin** [comment]
@vdemeester this should be addressed after #79 is fixed.
