### ISSUE TITLE
"List Taskrun" menu on a pipeline should only list the pipeline's taskrun

### ISSUE THREAD

**Issue by vdemeester** [redhat-developer/vscode-tekton#91]
Currently, it does only a `tkn taskrun list`, thus showing all the taskrun instead of the one related to the selected pipeline.

**Comment by dgolovin** [comment]
@vdemeester there is no `tkn` command to do this. Is `tkn describe` good replacement for that?

**Comment by vdemeester** [comment]
@dgolovin that's a good point :stuck_out_tongue_closed_eyes: we need a way to filter `tkn taskrun list` (and others) using label selector in `tkn`.

But yeah for now, I'm guessing we could have `tkn pipeline describe` instead

**Comment by siamaksade** [comment]
Relates to https://github.com/tektoncd/cli/issues/617

**Comment by siamaksade** [comment]
Wouldn't `tkn taskrun list | grep [pipelinerun-name]` give the same result right now?

**Comment by dgolovin** [comment]
yes, but only for users on linux and macOS machines.

**Comment by siamaksade** [comment]
Ah yea. Is there any equivalent command for Win? `findstr` perhaps

This is just a workaround till tektoncd/cli#617 is fixed. Another alternative is to remove the "List Taskrun" menu till filtering is added to the CLI

**Comment by siamaksade** [comment]
@evidolob right, specially given the new labels on the taskruns, we can just filter out the taskruns based on the pipelinerun label: https://github.com/tektoncd/pipeline/pull/2457
